---

- name: "lciolecki crontab manager"
  cron:
    backup:       "{{ item.backup|default(omit) }}"
    cron_file:    "{{ item.file|default(omit) }}"
    disabled:     "{{ item.disabled|default(omit) }}"
    name:         "{{ item.name }}"
    job:          "{{ item.job }}"
    minute:       "{{ item.minute|default(omit) }}"
    hour:         "{{ item.hour|default(omit) }}"
    day:          "{{ item.day|default(omit) }}"
    month:        "{{ item.month|default(omit) }}"
    weekday:      "{{ item.weekday|default(omit) }}"
    user:         "{{ item.user|default(item.user|default(omit)) }}"
    state:        "{{ item.state|default('present') }}"
    special_time: "{{ item.special_time|default(omit) }}"
  with_items: "{{ lciolecki_crons }}"
  notify:
    - cron restart
